[UI]
name = "FinPal"
description = "Your personal financial advisor."
custom_css = "public/custom.css"
# Optional: Custom JavaScript and CSS files for the frontend
#custom_js = "/public/js/chat.js"
#custom_css = "/public/css/style.css"

# Optional: Custom favicon
favicon = "/public/favicon.ico"
port = 8003

[features]
cloud = false

[custom]
public = "./public"